### ISSUE TITLE
使用shell_cmd_group报错，如下

### ISSUE THREAD

**Issue by maserzhao** [NevermindZZT/letter-shell#107]
![image](https://user-images.githubusercontent.com/48790454/140061825-493f5bbd-c99b-4984-b1f7-23f7cca0a59b.png)
代码有些看不太懂，不知道怎么改

**Comment by maserzhao** [comment]
![image](https://user-images.githubusercontent.com/48790454/140062169-d282ab9b-e7e0-4208-b4d3-ed32a87f705a.png)
原始就是这两个错误

**Comment by NevermindZZT** [comment]
> ![image](https://user-images.githubusercontent.com/48790454/140062169-d282ab9b-e7e0-4208-b4d3-ed32a87f705a.png) 原始就是这两个错误

第一个ITEM定义的时候，第一个参数不需要使用`SHELL_CMD_TYPE`宏(命令组中不需要)，至于这两个warning，如果不影响运行可以不用修改

**Comment by NevermindZZT** [comment]
> > ![image](https://user-images.githubusercontent.com/48790454/140062169-d282ab9b-e7e0-4208-b4d3-ed32a87f705a.png) 原始就是这两个错误
> 
> 第一个ITEM定义的时候，第一个参数不需要使用`SHELL_CMD_TYPE`宏(命令组中不需要)，至于这两个warning，如果不影响运行可以不用修改

这里编译器确实有点不兼容，我修改下

**Comment by NevermindZZT** [comment]
> > > ![image](https://user-images.githubusercontent.com/48790454/140062169-d282ab9b-e7e0-4208-b4d3-ed32a87f705a.png) 原始就是这两个错误
> > 
> > 
> > 第一个ITEM定义的时候，第一个参数不需要使用`SHELL_CMD_TYPE`宏(命令组中不需要)，至于这两个warning，如果不影响运行可以不用修改
> 
> 这里编译器确实有点不兼容，我修改下

已经修改好了，拉取最新的master分支代码就好

**Comment by maserzhao** [comment]
太感谢了！！！昨天半天都不知道咋改，多谢了
