### ISSUE TITLE
使用串口助手连接和发送字符串导致单片机卡死

### ISSUE THREAD

**Issue by zhbi98** [NevermindZZT/letter-shell#110]
自我诊断：
- [x] 我完全按照主页的 README 文档进行移植。
- [x] 我是用的单片机是 STM32F407。
- [x] 我使用的串口助手是 sscom5.13.1 这个版本。 

最终的现象是：

我按照文档进行移植创建 shell_port.c 和 shell_port.h 文件，创建全局 shell 变量，注册当前shell用户信息。创建全局buffer区，编写读字符函数，串口中断的回调函数，回调函数绑定为shellHandler，shell 的初始化，但是最终无法运行成功，并产生卡死问题。

**Comment by NevermindZZT** [comment]
是在中断里面调用的shellHanler吗，有些函数不能在中断里面运行，可以先添加一条空命令试试

**Comment by NevermindZZT** [comment]
shellHandler在中断里面调用，而不是使用shellHandler作为中断服务函数哦

**Comment by zhbi98** [comment]
是，我正是在中断函数中调用 shellHandler，就像下面这样。
```
void letter_shell_recv_irq_handler(UART_HandleTypeDef *huart)
{
    shellHandler(&shell, letter_shell_recv_buff);
    HAL_UART_Receive_IT(huart, &letter_shell_recv_buff, 1);
}
```

**Comment by NevermindZZT** [comment]
有试过跑一个空函数命令吗

**Comment by zhbi98** [comment]
我想确定一下，移植后只要使用 `shell.write = userShellWrite;`，`shell.read = userShellRead;`， `shellInit(&shell, shellBuffer, 512);` 初始化，就会输出 letter shell 样式的字符 logo 以及版本等信息吗？即使我没有注册命令。我一直输出是乱码，看不到这些信息。

**Comment by NevermindZZT** [comment]
shell.write函数被正确实现，再调用shellInit就能看到输出信息，乱码的话，确认下串口配置

**Comment by zhbi98** [comment]
OK 谢谢你的解答，就想确认一下移植成功的输出现象，但是还有一个问题是我的串口单独使用是没有乱码问题的

**Comment by NevermindZZT** [comment]
方便看一下shell.write的实现吗

**Comment by zhbi98** [comment]
这个方便，我的实现是这样子的，波特率是 115200，单片机使用的是 stm32f103zet6，固件库使用3.5版本的标准库
```
void usart_send_byte(USART_TypeDef * current_usart, unsigned char a_byte)
{
    USART_SendData(current_usart, a_byte);
    while (USART_GetFlagStatus(current_usart, USART_FLAG_TXE) == RESET);
}

void userShellWrite(unsigned char data)
{
    usart_send_byte(CURRENT_USART, data);
}
```

由于我一直移植 letter shell 3 版本不成功，所以我尝试移植了 letter shell 2 版本的分支，输出了以下信息：
```
+=========================================================+
|                (C) COPYRIGHT 2019 Letter                |
|                   Letter shell v2.0.8                   |
|               Build: Nov 21 2021 18:15:37               |
+=========================================================+

letter>>
```
所以我可以成功移植 版本2 的分支，但是移植版本 3一直乱码，这让我很不解，谢谢你能够耐心的帮助我。

**Comment by NevermindZZT** [comment]
是使用的3.1一上的版本吗，shell.write函数原型有修改

```c
    /**
     * @brief shell写数据函数原型
     *
     * @param data 需写的字符数据
     * @param len 需要写入的字符数
     *
     * @return unsigned short 实际写入的字符数量
     */
    typedef unsigned short (*shellWrite)(char *data, unsigned short len);
```

**Comment by zhbi98** [comment]
对就是这个问题，因为一直不理解所以查看了 master 具体源码发现了master 是最新版本，我一直移植的是 master 分支，因为我看到有一个分支是 3.1 版本，所以我以为 master 分支不是最新版本。所以没有仔细查看 master commit 信息，抱歉这是我的失误，多谢你的帮助。
