### ISSUE TITLE
用户名和命令使用了相同的字符串，shellInit会错误初始化用户，导致异常

### ISSUE THREAD

**Issue by zbianbiaos** [NevermindZZT/letter-shell#117]
命令存放在DATA.RO section内
`
#define  SHELL_USING_CMD_EXPORT   1
`

在调用shellInit初始化shell，有如下函数
`c
shellSetUser(shell, shellSeekCommand(shell,
                                         SHELL_DEFAULT_USER,
                                         shell->commandList.base,
                                         0));
`
是通过shellSeekCommand方式查找默认用户注册，此处我设置
`c
#define     SHELL_DEFAULT_USER          "bms"
`
然后同样注册了一个命令
`c
SHELL_EXPORT_CMD(
SHELL_CMD_PERMISSION(0)|SHELL_CMD_TYPE(SHELL_TYPE_CMD_FUNC)|SHELL_CMD_DISABLE_RETURN,
bms, bms_command, bms command);
`
shellSeekCommand的时候会把bms_command作为用户类型输入了shellSetUser，导致异常

**Comment by NevermindZZT** [comment]
用户本身也是命令的一种，同名的话会产生冲突的

**Comment by lotoohe-space** [comment]
你好，邮件已收到，谢谢！
