### ISSUE TITLE
letter-shell 移植到国产的hk32弹片击上，运行不了

### ISSUE THREAD

**Issue by leadercxn** [NevermindZZT/letter-shell#118]
1. 你好，我移植了你们的letter-shell到国产hk32的单片机平台上，工程demo，使用的是mac版本的gcc去编译的，ld脚本已按照要求添加了相关字段，但在使用 shellInit() 函数的时候，程序就卡死了，我的工程路径链接是 [demo](https://github.com/leadercxn/app-demo),查了很久也没发现什么问题，麻烦帮忙查查原因？

**Comment by lotoohe-space** [comment]
你好，邮件已收到，谢谢！

**Comment by NevermindZZT** [comment]
> 1. 你好，我移植了你们的letter-shell到国产hk32的单片机平台上，工程demo，使用的是mac版本的gcc去编译的，ld脚本已按照要求添加了相关字段，但在使用 shellInit() 函数的时候，程序就卡死了，我的工程路径链接是 [demo](https://github.com/leadercxn/app-demo),查了很久也没发现什么问题，麻烦帮忙查查原因？

加上字节对齐试试
```ld
  /* Constant data goes into FLASH */
  .rodata :
  {
    . = ALIGN(4);
    *(.rodata)         /* .rodata sections (constants, strings, etc.) */
    *(.rodata*)        /* .rodata* sections (constants, strings, etc.) */
    . = ALIGN(4);
    _shell_command_start = .;
    KEEP (*(shellCommand))
    _shell_command_end = .;
    . = ALIGN(4);
  } >FLASH
```

**Comment by leadercxn** [comment]
> > 1. 你好，我移植了你们的letter-shell到国产hk32的单片机平台上，工程demo，使用的是mac版本的gcc去编译的，ld脚本已按照要求添加了相关字段，但在使用 shellInit() 函数的时候，程序就卡死了，我的工程路径链接是 [demo](https://github.com/leadercxn/app-demo),查了很久也没发现什么问题，麻烦帮忙查查原因？
> 
> 加上字节对齐试试
> 
> ```
>   /* Constant data goes into FLASH */
>   .rodata :
>   {
>     . = ALIGN(4);
>     *(.rodata)         /* .rodata sections (constants, strings, etc.) */
>     *(.rodata*)        /* .rodata* sections (constants, strings, etc.) */
>     . = ALIGN(4);
>     _shell_command_start = .;
>     KEEP (*(shellCommand))
>     _shell_command_end = .;
>     . = ALIGN(4);
>   } >FLASH
> ```

@NevermindZZT  现在可以输出了，但就是疯狂输出....letter shell 的字样
![letter-shell](https://user-images.githubusercontent.com/43691182/163815023-6099fb7e-1fdf-4bfb-a109-5bf2d70c6b7e.png)

**Comment by NevermindZZT** [comment]
> > > 1. 你好，我移植了你们的letter-shell到国产hk32的单片机平台上，工程demo，使用的是mac版本的gcc去编译的，ld脚本已按照要求添加了相关字段，但在使用 shellInit() 函数的时候，程序就卡死了，我的工程路径链接是 [demo](https://github.com/leadercxn/app-demo),查了很久也没发现什么问题，麻烦帮忙查查原因？
> > 
> > 
> > 加上字节对齐试试
> > ```
> >   /* Constant data goes into FLASH */
> >   .rodata :
> >   {
> >     . = ALIGN(4);
> >     *(.rodata)         /* .rodata sections (constants, strings, etc.) */
> >     *(.rodata*)        /* .rodata* sections (constants, strings, etc.) */
> >     . = ALIGN(4);
> >     _shell_command_start = .;
> >     KEEP (*(shellCommand))
> >     _shell_command_end = .;
> >     . = ALIGN(4);
> >   } >FLASH
> > ```
> 
> @NevermindZZT 现在可以输出了，但就是疯狂输出....letter shell 的字样 ![letter-shell](https://user-images.githubusercontent.com/43691182/163815023-6099fb7e-1fdf-4bfb-a109-5bf2d70c6b7e.png)

看起来程序挂掉了，检查一下串口驱动

**Comment by leadercxn** [comment]
> > > > 1. 你好，我移植了你们的letter-shell到国产hk32的单片机平台上，工程demo，使用的是mac版本的gcc去编译的，ld脚本已按照要求添加了相关字段，但在使用 shellInit() 函数的时候，程序就卡死了，我的工程路径链接是 [demo](https://github.com/leadercxn/app-demo),查了很久也没发现什么问题，麻烦帮忙查查原因？
> > > 
> > > 
> > > 加上字节对齐试试
> > > ```
> > >   /* Constant data goes into FLASH */
> > >   .rodata :
> > >   {
> > >     . = ALIGN(4);
> > >     *(.rodata)         /* .rodata sections (constants, strings, etc.) */
> > >     *(.rodata*)        /* .rodata* sections (constants, strings, etc.) */
> > >     . = ALIGN(4);
> > >     _shell_command_start = .;
> > >     KEEP (*(shellCommand))
> > >     _shell_command_end = .;
> > >     . = ALIGN(4);
> > >   } >FLASH
> > > ```
> > 
> > 
> > @NevermindZZT 现在可以输出了，但就是疯狂输出....letter shell 的字样 ![letter-shell](https://user-images.githubusercontent.com/43691182/163815023-6099fb7e-1fdf-4bfb-a109-5bf2d70c6b7e.png)
> 
> 看起来程序挂掉了，检查一下串口驱动

是的，我的驱动有BUG，已解决。谢谢！
![image](https://user-images.githubusercontent.com/43691182/163824810-f4eb691e-9a6f-4bdd-add2-77e7f8a5606b.png)
