### ISSUE TITLE
ESP32-idf4.4使用问题

### ISSUE THREAD

**Issue by sonnyyin** [NevermindZZT/letter-shell#121]
您好，我一直在STM32上使用lettershell，最近想移植到ESP32上使用，目前在idf-4.4框架下编译正常，也修改了D:\Espressif\frameworks\esp-idf-v4.4\components\esp_system\ld\esp32\sections.ld.in  中的内容，但是下载后看不到熟悉的提示语及shell界面，麻烦帮忙看下。
![图片](https://user-images.githubusercontent.com/33096611/167239160-5afc80ab-c169-44ee-8e17-3f0ea5deb87a.png)

运行时显示如下：
![图片](https://user-images.githubusercontent.com/33096611/167239195-93f65fed-2451-4872-9512-43b9f7d5294b.png)

代码使用的esp-idf中的port文件，未做修改
![图片](https://user-images.githubusercontent.com/33096611/167239220-338c175e-bc7a-4fdb-ae6c-843ef4487c16.png)

**Comment by sonnyyin** [comment]
[lettershell-test.zip](https://github.com/NevermindZZT/letter-shell/files/8644502/lettershell-test.zip)

**Comment by NevermindZZT** [comment]
esp-idf 的 demo 需要更新，明天我更新一下

**Comment by sonnyyin** [comment]
> esp-idf 的 demo 需要更新，明天我更新一下

好的，谢谢！

**Comment by NevermindZZT** [comment]
#122 已更新

**Comment by sonnyyin** [comment]
目前测试情况，在wifi未连接时，shell输入输出正常，设置wifi-sta模式，连接AP后，CRT端输入异常，很难接收到输入的键值（键值无回显），不知道是不是wifi里面也有什么阻塞了，准备试一下改成队列是否有改善。

**Comment by sonnyyin** [comment]
使用队列读取数据依然存在以上现象，关闭wifi任务后，队列读取数据也是正常的。能否协助查找原因？

**Comment by NevermindZZT** [comment]
你用的是哪个型号，这个有时间我再试试，之前都是可以的

**Comment by sonnyyin** [comment]
esp32-WROOM-32U  内部ESP32-D0WD (revision 1)

**Comment by sonnyyin** [comment]
void wifi_init_sta(wifiports_stainfo_t *sta_info)
{
	//使用WiFi前必须先初始化NVS存储，若之前没有初始化NVS分区，则打开以下几行注释
	// esp_err_t ret = nvs_flash_init();
    // if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) 
    // {
    //     ESP_LOGE(TAG,"NVS初始化失败！");
	// 	ESP_LOGE(TAG,"格式化NVS分区！");
	// 	ESP_ERROR_CHECK(nvs_flash_erase());
	// 	ret = nvs_flash_init();
    // }
    // ESP_ERROR_CHECK( ret );

	//开启lightsleep 省电模式
	wifi_light_sleep_config(DEFAULT_MIN_FREQ,DEFAULT_MAX_FREQ,USE_LIGHT_SLEEP_MODE);
	//tcp/ip初始化
    ESP_ERROR_CHECK(esp_netif_init());
	//创建默认的循环事件
	ESP_ERROR_CHECK(esp_event_loop_create_default());
    // ESP_ERROR_CHECK(esp_event_loop_init(event_handler,NULL));
	// 创建具有TCP/ip堆栈的默认网络接口实例绑定基站
    esp_netif_t *sta_netif = esp_netif_create_default_wifi_sta();
	//设置hostname名称,获取MAC地址组合成hostname
	char *host_name = sta_get_wifi_hostname();
	esp_netif_set_hostname(sta_netif,host_name);
	//创建wifi默认配置结构体函数
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
	//初始化wifi
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

	static wifiports_info_t	wifi_info;
	wifi_info.netif = sta_netif;
	wifi_info.stainfo = sta_info;
	
    esp_event_handler_instance_t instance_any_id;
    esp_event_handler_instance_t instance_got_ip;
	//向默认循环注册WIFI_EVENT处理程序实例,同时传入WiFi相关信息，用于处理相关任务
    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
                                                        ESP_EVENT_ANY_ID,
                                                        &event_handler,
                                                        &wifi_info,
                                                        &instance_any_id));
	//向默认循环注册IP_EVENT处理程序实例														
    ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT,
                                                        IP_EVENT_STA_GOT_IP,
                                                        &event_handler,
                                                        &wifi_info,
                                                        &instance_got_ip));
	//设置一个默认的wifi配置，如果传入NULL，则使用默认配置连接wifi，一般用于内部测试时候使用
    wifi_config_t default_wifi_sta_config = {
        .sta = {
            .ssid 		= DEFAULT_WIFI_SSID,
            .password 	= DEFAULT_WIFI_PASSWORD,
            .pmf_cfg = {
                .capable = true,
                .required = false
            },
			.listen_interval = DEFAULT_LISTEN_INTERVAL,
        },
    };
	if ((sta_info!=NULL) && (strlen(sta_info->ssid) > 0))
	{
		strcpy((char *)default_wifi_sta_config.sta.ssid,sta_info->ssid);
		strcpy((char *)default_wifi_sta_config.sta.password,sta_info->password);
	}
	
	//设置wifi模式为STATION模式
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
	//写入wifi参数
	ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &default_wifi_sta_config));
	//开启wifi
    ESP_ERROR_CHECK(esp_wifi_start() );
    ESP_LOGI(TAG, "wifi_init_sta finished.");
	if (USE_LIGHT_SLEEP_MODE)
	{
		esp_wifi_set_ps(DEFAULT_PS_MODE);
	}
}

这个是我的初始化代码

**Comment by NevermindZZT** [comment]
[esp32_shell.zip](https://github.com/NevermindZZT/letter-shell/files/8691997/esp32_shell.zip)
我这里直接用 esp-idf 的连接代码是 OK 的，您可以参考下

**Comment by sonnyyin** [comment]
上传的附件工程无法打开，C文件与H文件全是乱码，麻烦重新上传一下吧，谢谢

**Comment by sonnyyin** [comment]
已找到原因了，是因为我使用了省电模式造成的，关闭省电模式现在正常了，感谢！

**Comment by sonnyyin** [comment]
又遇到一个问题，在将CMD权限设置为非0时，运行出错，应该是检查用户有没有命令权限时候出错了。日志截图如下：

![image](https://user-images.githubusercontent.com/33096611/168442138-c6722392-b888-41d7-8e64-9a60f3dcf812.png)

![image](https://user-images.githubusercontent.com/33096611/168442240-5ddeba67-0cf3-41aa-9319-67d739cdebb0.png)

**Comment by NevermindZZT** [comment]
> 又遇到一个问题，在将CMD权限设置为非0时，运行出错，应该是检查用户有没有命令权限时候出错了。日志截图如下：
> 
> ![image](https://user-images.githubusercontent.com/33096611/168442138-c6722392-b888-41d7-8e64-9a60f3dcf812.png)
> 
> ![image](https://user-images.githubusercontent.com/33096611/168442240-5ddeba67-0cf3-41aa-9319-67d739cdebb0.png)

是有个问题，已修复 #123

**Comment by sonnyyin** [comment]
这个是我修改过的shell，里面加了用户输入密码用星号显示及密码错误重试次数计数，用户退出命令，需要的朋友可以下载。再次感谢 @NevermindZZT 帮助！
[shell.zip](https://github.com/NevermindZZT/letter-shell/files/8694943/shell.zip)

https://user-images.githubusercontent.com/33096611/168473732-bf37d152-a371-4eb8-89fc-81239cac580f.mp4

**Comment by sonnyyin** [comment]
目前测试CMD命令权限已经正常了，其他功能待进一步测试后反馈，谢谢帮助！
