### ISSUE TITLE
尾行模式时候，输入用户名密码异常

### ISSUE THREAD

**Issue by sonnyyin** [NevermindZZT/letter-shell#124]
在使用尾行模式时候，如果切换带密码的用户，在输入密码时候，尾行模式的数据会刷新输入，造成密码输入异常，目前我的解决方案是在切换用户时候禁用尾行模式，不知道有没有更好的方案。

![图片](https://user-images.githubusercontent.com/33096611/168802342-5a7f35fd-24b3-426d-bd92-264496b54527.png)

我这修改了比较多的源码，不知道是不是我的修改也影响了尾行模式。

**Comment by sonnyyin** [comment]
这个问题应该跟我修改了代码有点关系，目前修改了输入密码使用星号掩盖，尝试次数可以设定，目前设定为3次。使用自己移植的log组件输出3条日志就会报尝试登陆失败，如果中间输入了部分密码，在尾行模式刷新时，已输入的密码就会被显示出来。

**Comment by NevermindZZT** [comment]
尾行模式应该是没有考虑密码输入的，这个可能本身就有问题

**Comment by sonnyyin** [comment]
![图片](https://user-images.githubusercontent.com/33096611/201505329-ca91a3c6-c185-4aa9-864b-f41deb33ed7a.png)
可以参考一下，自己实现的！
