### ISSUE TITLE
STM32F107移植LetterShell + LWIP TCP初始化后，报HardFault

### ISSUE THREAD

**Issue by youzhouchang** [NevermindZZT/letter-shell#127]
我在STM32F107裸机移植成功LetterShell后，又加入了LWIP，然后初始化TCP（RAW API）后，程序运行直接报HardFault，换成UDP初始化是OK的，，或者屏蔽LetterShell后单独测试TCP和UDP是OK的，这两个似乎不能共存。尝试放大堆栈空间依旧无效。

**Comment by NevermindZZT** [comment]
查一下调用栈，这两个不会有直接关联的

**Comment by youzhouchang** [comment]
是我的问题，TCP开销比UDP大，导致我的程序堆栈溢出
