### ISSUE TITLE
基于UDP实现letter shell

### ISSUE THREAD

**Issue by youzhouchang** [NevermindZZT/letter-shell#134]
请教一下有没有基于UDP通信实现letter shell的方案。个人觉得UDP不用维护连接状态，开销比TCP小，letter shell是通过串口中断输入单个字符传递给句柄的做处理的，我使用netcat模拟终端的时候发现netcat必须使用回车才可以发送输入的字符或者字符串，那这样的话方案是不是行不通？

**Comment by NevermindZZT** [comment]
可以用UDP做，和TCP一样的，只是换一个网络连接方式而已
单个字符传输是为了终端的回显和自动补全等一些特性，你说用netcat是按回车才发送，这个不会影响到命令执行的
