### ISSUE TITLE
letter-shell是通过什么方式确定函数传入参数的个数？

### ISSUE THREAD

**Issue by tsk15535904190** [NevermindZZT/letter-shell#136]
参数数量储存在ShellCommand.attr.attrs.paramNum中，与之共享内存的是value，但是我找不到在哪个地方对其赋值，请您给予一些指导。

**Comment by NevermindZZT** [comment]
分两个情况，一个是在声明命令的时候使用SHELL_CMD_PARAM_NUM(num) 指定，如果不指定，会以命令行获取到的参数数量为准

**Comment by tsk15535904190** [comment]
感谢
