### ISSUE TITLE
STM32 gcc 编译后，输入命令会卡死，跳到HardFault_Handler中断.

### ISSUE THREAD

**Issue by panguoxian** [NevermindZZT/letter-shell#14]
这是一个很棒的工程，但是GCC编译会有些问题希望能有更好的支持。

STM32 gcc 编译后，输入命令会卡死，跳到HardFault_Handler中断.

MDK编译，正常。

**Comment by panguoxian** [comment]
问题已解决，没有在ld文件件中添加
_shell_command_start = .;
KEEP (*(shellCommand))
_shell_command_end = .;

**Comment by xyz502** [comment]
怎么添加呢
