### ISSUE TITLE
SHELL_EXPORT_CMD命令未生效

### ISSUE THREAD

**Issue by Blueknife-w** [NevermindZZT/letter-shell#142]
**环境描述**

+ Code Version: [5c35f03](https://github.com/NevermindZZT/letter-shell/commit/5c35f032d177acb1ea7333202616a484b73bac27)

+ 控制器：ESP32-WROOM-32UE

**问题描述:**
+ 我创建一个新的文件，包含头文件`#include "shell.h"`，在此文件内调用readme.mk里面的SHELL_EXPORT_CMD注册函数命令，之后下载运行程序，在命令列表内并没有找到对应的命令，无法执行命令；

+ 尝试在example目录内自带的shell_port.c文件内添加函数，并采用SHELL_EXPORT_CMD注册函数命令，之后下载运行，在命令列表内可见此命令，可正常调用；

+ 已确认新建的文件已被编译链接，`SHELL_SHOW_INFO` 宏已打开`#define     SHELL_SHOW_INFO             1`

+ 请问执行`SHELL_EXPORT_CMD`的文件有什么特殊要求吗？为什么在自己新建的文件内无法执行，而在已有的文件内可以被正常执行？

![image](https://user-images.githubusercontent.com/52915612/222400849-5584971a-bfbc-4e7c-a579-48a42d2e3e6e.png)

![image](https://user-images.githubusercontent.com/52915612/222401318-ea124276-0ef7-402d-9fbb-450a33e80fc9.png)

![image](https://user-images.githubusercontent.com/52915612/222401745-008ee148-3f1d-41c5-8476-f19c5c463e92.png)

![image](https://user-images.githubusercontent.com/52915612/222401874-3afac16f-a200-466b-9936-1715131efb47.png)

**Comment by NevermindZZT** [comment]
这个其实是 esp-idf 的问题，esp-idf 仓库下也有人反馈这个问题，但是乐鑫看着并不想改

原因是 esp-idf 编译的时候，是按照一个一个模块编译的，每个模块编译成一个库文件，编译库的时候，会强行将定义但未使用的符号优化掉，哪怕增加了 keep 声明

所以在 shell 这个模块外导出的命令，会被优化掉，有几种方案，一是将所有的命令定义放到 shell 这个模块，二是写一个函数，将所有定义的命令对应的函数引用一下，三是干脆不分模块，所有的代码都放在一起用一个CmakeLists.txt 声明

**Comment by NevermindZZT** [comment]
还有个方法是直接修改 esp-idf 总的那个 ld 文件

**Comment by Blueknife-w** [comment]
首先感谢作者的回复，发现确实是ESP-IDF的问题导致

此外我发现一种更好的处理方式：
+ 我尝试在新建的文件内增加了一个普通函数，之后在其他地方调用了这个函数，从而使得ESP-IDF不直接优化掉整个文件，经验证此方法有效

![image](https://user-images.githubusercontent.com/52915612/222614769-9bf10d69-7a97-4808-a4d0-78c114de95f1.png)

![image](https://user-images.githubusercontent.com/52915612/222614958-ef292903-18ec-4301-bd19-3bf906c5da25.png)

**Comment by YannnnR** [comment]
这样也行 可以针对func1函数，取消编译优化：
#pragma GCC push_options
#pragma GCC optimize("O0")
void func1()
{
    Serial0.println("fdfasdfa");
}
SHELL_EXPORT_CMD(func1, func1, func1);
![image](https://github.com/NevermindZZT/letter-shell/assets/57860566/14496846-c974-4be9-b18a-4f5d7999bc0e)
