### ISSUE TITLE
shell read读取长度问题

### ISSUE THREAD

**Issue by fyyxxm** [NevermindZZT/letter-shell#150]
shell_read
这个函数是默认读取长度为1.
如果读取上下左右键，就要读取三次，然后shell才去处理，这效率太低了吧。

不可以把实际读取到的长度返回给shell，让shell处理吗。。。
比如读取方向键，uart可以直接读到 3个数据，把长度返回给shell，shell一次性处理。这样更好吧。。。。

**Comment by NevermindZZT** [comment]
也有单个数据的键值，都是需要直接处理的，而且就算这些按键多个字节一起输入，也是需要一个一个处理的

**Comment by fyyxxm** [comment]
其实不只是键值的数据，还有命令的数据，其实单个的键值这种情况并不多，大部分都是输入的不定长的shell指令。
