### ISSUE TITLE
使用STM32CubeIDE移植Letter-Shell出现HardFault问题。

### ISSUE THREAD

**Issue by Home-Laozang** [NevermindZZT/letter-shell#162]
按照说明问题进行移植的，但是下载执行就进入Hardfault，新建MDK工程是没有问题的，但是同样存在退出在线调试后，再次进入调试出现不执行到Main函数入口。只能将板卡断电重启才行，RESET引脚复位没有效果。
<img width="700" alt="00" src="https://github.com/NevermindZZT/letter-shell/assets/52019342/9386d83a-622a-4c21-8e56-bf1db32d03c6">
<img width="785" alt="01" src="https://github.com/NevermindZZT/letter-shell/assets/52019342/96704238-035a-4523-94ba-7837c3b4f851">
代码运行到这里就进入Hardfault，访问了的错误的地址空间。

**Comment by Home-Laozang** [comment]
<img width="581" alt="03" src="https://github.com/NevermindZZT/letter-shell/assets/52019342/147e8886-b3e7-46fe-b25a-f6e06cd859bd">
 代码运行到这里就Hardfault中断

**Comment by NevermindZZT** [comment]
可能是数据没对齐，在ld文件的 _shell_command_start 前面加 .＝ ALIGN(4) 试试，如果还不行可以放下 map 文件看看

**Comment by Home-Laozang** [comment]
`
.rodata         0x000000000800498c      0x5e8
                0x000000000800498c                . = ALIGN (0x4)
 *(.rodata)
 .rodata        0x000000000800498c       0x10 ./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.o
 .rodata        0x000000000800499c      0x2f1 ./LetterShell/src/shell.o
 *(.rodata*)
 *fill*         0x0000000008004c8d        0x3 
 .rodata.shellCmdLED1_Pin_Set
                0x0000000008004c90        0xd ./Core/Src/main.o
                0x0000000008004c90                shellCmdLED1_Pin_Set
 *fill*         0x0000000008004c9d        0x3 
 .rodata.shellDescLED1_Pin_Set
                0x0000000008004ca0       0x26 ./Core/Src/main.o
                0x0000000008004ca0                shellDescLED1_Pin_Set
 *fill*         0x0000000008004cc6        0x2 
 .rodata.shellCmdLED2_Pin_Set
                0x0000000008004cc8        0xd ./Core/Src/main.o
                0x0000000008004cc8                shellCmdLED2_Pin_Set
 *fill*         0x0000000008004cd5        0x3 
 .rodata.shellDescLED2_Pin_Set
                0x0000000008004cd8       0x26 ./Core/Src/main.o
                0x0000000008004cd8                shellDescLED2_Pin_Set
 *fill*         0x0000000008004cfe        0x2 
 .rodata.AHBPrescTable
                0x0000000008004d00       0x10 ./Core/Src/system_stm32f1xx.o
                0x0000000008004d00                AHBPrescTable
 .rodata.APBPrescTable
                0x0000000008004d10        0x8 ./Core/Src/system_stm32f1xx.o
                0x0000000008004d10                APBPrescTable
 .rodata.shellCmdDefaultUser
                0x0000000008004d18        0x7 ./LetterShell/src/shell.o
                0x0000000008004d18                shellCmdDefaultUser
 *fill*         0x0000000008004d1f        0x1 
 .rodata.shellPasswordDefaultUser
                0x0000000008004d20        0x1 ./LetterShell/src/shell.o
                0x0000000008004d20                shellPasswordDefaultUser
 *fill*         0x0000000008004d21        0x3 
 .rodata.shellDesDefaultUser
                0x0000000008004d24        0xd ./LetterShell/src/shell.o
                0x0000000008004d24                shellDesDefaultUser
 *fill*         0x0000000008004d31        0x3 
 .rodata.shellCmdsetVar
                0x0000000008004d34        0x7 ./LetterShell/src/shell.o
                0x0000000008004d34                shellCmdsetVar
 *fill*         0x0000000008004d3b        0x1 
 .rodata.shellDescsetVar
                0x0000000008004d3c        0x8 ./LetterShell/src/shell.o
                0x0000000008004d3c                shellDescsetVar
 .rodata.shellDesc0x1B5B4100
                0x0000000008004d44        0x3 ./LetterShell/src/shell.o
                0x0000000008004d44                shellDesc0x1B5B4100
 *fill*         0x0000000008004d47        0x1 
 .rodata.shellDesc0x1B5B4200
                0x0000000008004d48        0x5 ./LetterShell/src/shell.o
                0x0000000008004d48                shellDesc0x1B5B4200
 *fill*         0x0000000008004d4d        0x3 
 .rodata.shellDesc0x1B5B4300
                0x0000000008004d50        0x6 ./LetterShell/src/shell.o
                0x0000000008004d50                shellDesc0x1B5B4300
 *fill*         0x0000000008004d56        0x2 
 .rodata.shellDesc0x1B5B4400
                0x0000000008004d58        0x5 ./LetterShell/src/shell.o
                0x0000000008004d58                shellDesc0x1B5B4400
 *fill*         0x0000000008004d5d        0x3 
 .rodata.shellDesc0x09000000
                0x0000000008004d60        0x4 ./LetterShell/src/shell.o
                0x0000000008004d60                shellDesc0x09000000
 .rodata.shellDesc0x08000000
                0x0000000008004d64        0xa ./LetterShell/src/shell.o
                0x0000000008004d64                shellDesc0x08000000
 *fill*         0x0000000008004d6e        0x2 
 .rodata.shellDesc0x7F000000
                0x0000000008004d70        0xa ./LetterShell/src/shell.o
                0x0000000008004d70                shellDesc0x7F000000
 *fill*         0x0000000008004d7a        0x2 
 .rodata.shellDesc0x1B5B337E
                0x0000000008004d7c        0x7 ./LetterShell/src/shell.o
                0x0000000008004d7c                shellDesc0x1B5B337E
 *fill*         0x0000000008004d83        0x1 
 .rodata.shellDesc0x0A000000
                0x0000000008004d84        0x6 ./LetterShell/src/shell.o
                0x0000000008004d84                shellDesc0x0A000000
 *fill*         0x0000000008004d8a        0x2 
 .rodata.shellDesc0x0D000000
                0x0000000008004d8c        0x6 ./LetterShell/src/shell.o
                0x0000000008004d8c                shellDesc0x0D000000
 *fill*         0x0000000008004d92        0x2 
 .rodata.shellCmdhelp
                0x0000000008004d94        0x5 ./LetterShell/src/shell.o
                0x0000000008004d94                shellCmdhelp
 *fill*         0x0000000008004d99        0x3 
 .rodata.shellDeschelp
                0x0000000008004d9c       0x1e ./LetterShell/src/shell.o
                0x0000000008004d9c                shellDeschelp
 *fill*         0x0000000008004dba        0x2 
 .rodata.shellCmdusers
                0x0000000008004dbc        0x6 ./LetterShell/src/shell.o
                0x0000000008004dbc                shellCmdusers
 *fill*         0x0000000008004dc2        0x2 
 .rodata.shellDescusers
                0x0000000008004dc4        0xe ./LetterShell/src/shell.o
                0x0000000008004dc4                shellDescusers
 *fill*         0x0000000008004dd2        0x2 
 .rodata.shellCmdcmds
                0x0000000008004dd4        0x5 ./LetterShell/src/shell.o
                0x0000000008004dd4                shellCmdcmds
 *fill*         0x0000000008004dd9        0x3 
 .rodata.shellDesccmds
                0x0000000008004ddc        0xd ./LetterShell/src/shell.o
                0x0000000008004ddc                shellDesccmds
 *fill*         0x0000000008004de9        0x3 
 .rodata.shellCmdvars
                0x0000000008004dec        0x5 ./LetterShell/src/shell.o
                0x0000000008004dec                shellCmdvars
 *fill*         0x0000000008004df1        0x3 
 .rodata.shellDescvars
                0x0000000008004df4        0xd ./LetterShell/src/shell.o
                0x0000000008004df4                shellDescvars
 *fill*         0x0000000008004e01        0x3 
 .rodata.shellCmdkeys
                0x0000000008004e04        0x5 ./LetterShell/src/shell.o
                0x0000000008004e04                shellCmdkeys
 *fill*         0x0000000008004e09        0x3 
 .rodata.shellDesckeys
                0x0000000008004e0c        0xd ./LetterShell/src/shell.o
                0x0000000008004e0c                shellDesckeys
 *fill*         0x0000000008004e19        0x3 
 .rodata.shellCmdclear
                0x0000000008004e1c        0x6 ./LetterShell/src/shell.o
                0x0000000008004e1c                shellCmdclear
 *fill*         0x0000000008004e22        0x2 
 .rodata.shellDescclear
                0x0000000008004e24        0xe ./LetterShell/src/shell.o
                0x0000000008004e24                shellDescclear
                0x0000000008004e32                _shell_command_start = .
 *(shellCommand)
 *fill*         0x0000000008004e32        0x2 
 shellCommand   0x0000000008004e34       0x20 ./Core/Src/main.o
                0x0000000008004e34                shellCommandLED1_Pin_Set
                0x0000000008004e44                shellCommandLED2_Pin_Set
 shellCommand   0x0000000008004e54      0x120 ./LetterShell/src/shell.o
                0x0000000008004e54                shellUserDefault
                0x0000000008004e64                shellCommandsetVar
                0x0000000008004e74                shellKey0x1B5B4100
                0x0000000008004e84                shellKey0x1B5B4200
                0x0000000008004e94                shellKey0x1B5B4300
                0x0000000008004ea4                shellKey0x1B5B4400
                0x0000000008004eb4                shellKey0x09000000
                0x0000000008004ec4                shellKey0x08000000
                0x0000000008004ed4                shellKey0x7F000000
                0x0000000008004ee4                shellKey0x1B5B337E
                0x0000000008004ef4                shellKey0x0A000000
                0x0000000008004f04                shellKey0x0D000000
                0x0000000008004f14                shellCommandhelp
                0x0000000008004f24                shellCommandusers
                0x0000000008004f34                shellCommandcmds
                0x0000000008004f44                shellCommandvars
                0x0000000008004f54                shellCommandkeys
                0x0000000008004f64                shellCommandclear
                0x0000000008004f74                _shell_command_end = .
                0x0000000008004f74                . = ALIGN (0x4)
`

这个是map文件的部分

**Comment by NevermindZZT** [comment]
是不是在 main.c 文件有一个 shellCommand 定义，这个定义的是什么，看着是这个定义有问题，不要使用 shellCommand* 定义变量，会影响命令表

**Comment by Home-Laozang** [comment]
![map](https://github.com/NevermindZZT/letter-shell/assets/52019342/e95fad3d-f5a1-4086-a992-8268e5daf27f)
map文件

**Comment by Home-Laozang** [comment]
这是MAIN.c里面唯一关于命令导出的代码了
![code](https://github.com/NevermindZZT/letter-shell/assets/52019342/e378357d-28a4-4a15-8e9e-7e98938d8a36)

**Comment by NevermindZZT** [comment]
看到问题了，就是没有对齐，看你 map 文件，没在 ld 文件声明 _shell_command_start 前增加 ALIGN ？

**Comment by Home-Laozang** [comment]
<img width="461" alt="1188" src="https://github.com/NevermindZZT/letter-shell/assets/52019342/0aa34b16-4d67-4f05-a126-ab04dd33d46b">
这里是有对齐的呀，难道不是这样写的？

**Comment by NevermindZZT** [comment]
在 _shell_cimmand_start 上面一行，再加一条 ALIGN

**Comment by NevermindZZT** [comment]
ld 文件修改为

```ld
.rodata
{
  .  = ALIGN(4);
  *(.rodata)
  /* 原本内容省略 */
  . = ALIGN(4);  /* 这里多添加一句对齐 */
  _shell_command_start = .;
  KEEP (*(shellCommand))
  _shell_command_end = .;
  . = ALIGN(4);
}
````

**Comment by Home-Laozang** [comment]
谢谢，确实是这个原因
