### ISSUE TITLE
SecureCRT输入到单片机的数据异常

### ISSUE THREAD

**Issue by Home-Laozang** [NevermindZZT/letter-shell#179]
大佬你好，我移植测试是正常的，但是在交互时发现如下问题。
就是我键盘的输入，和终端发送到单片机的数据不一样。
比如我输入的字符G，单片机得到的数据却是*。输入其他字符也是*。
其次，我使用方向键，按理说有5条记录的命令可用的，按方向键没有反应。然后就会输入一些莫名其妙的字符出来。

代码如下：
`void Server_IPEdit(char ch)
{
    char *Server_IP_ptr;

    shellPrint(&shell, "cmd:%c\r\n", ch);
    switch (ch)
    {
    case 'G':
        Server_IP_ptr = ef_get_env("Server_IP");
        shellPrint(&shell, "Server_IP:%s\r\n", Server_IP_ptr);
        break;

    case 'S':
        // ef_set_env("Server_IP", para);
        // ef_save_env();
        break;

    case 'H':
        shellPrint(&shell, "Server_IP: G:Get IP Addr\nS:Set IP addr,follow ip address\nH:Help\r\n");
        break;

    default:
        shellPrint(&shell, "Param Error, Input correct parameters:G:Get,S:Set,H:Help\r\n");
        break;
    }
}
SHELL_EXPORT_CMD(SHELL_CMD_PERMISSION(0) | SHELL_CMD_TYPE(SHELL_TYPE_CMD_FUNC) | SHELL_CMD_DISABLE_RETURN, Server_IP, Server_IPEdit, 设置获取服务器IP地址\r\n格式 : Server_IP[cmd][params]);
`

**Comment by Home-Laozang** [comment]
![image](https://github.com/NevermindZZT/letter-shell/assets/52019342/96c3e7cb-e2a8-4aab-a81b-72fb6e8b604c)

**Comment by Home-Laozang** [comment]
另外还请教一个事，“--keep shellCommand*”这个是放在options for target中Linker选项卡吧，因为我放C/C++或者Asm选项卡下均出现编译错误

**Comment by NevermindZZT** [comment]
> 另外还请教一个事，“--keep shellCommand*”这个是放在options for target中Linker选项卡吧，因为我放C/C++或者Asm选项卡下均出现编译错误

这个是对的

**Comment by NevermindZZT** [comment]
> 大佬你好，我移植测试是正常的，但是在交互时发现如下问题。 就是我键盘的输入，和终端发送到单片机的数据不一样。 比如我输入的字符G，单片机得到的数据却是*。输入其他字符也是*。 其次，我使用方向键，按理说有5条记录的命令可用的，按方向键没有反应。然后就会输入一些莫名其妙的字符出来。
> 
> 代码如下： `void Server_IPEdit(char ch) { char *Server_IP_ptr;
> 
> ```
> shellPrint(&shell, "cmd:%c\r\n", ch);
> switch (ch)
> {
> case 'G':
>     Server_IP_ptr = ef_get_env("Server_IP");
>     shellPrint(&shell, "Server_IP:%s\r\n", Server_IP_ptr);
>     break;
> 
> case 'S':
>     // ef_set_env("Server_IP", para);
>     // ef_save_env();
>     break;
> 
> case 'H':
>     shellPrint(&shell, "Server_IP: G:Get IP Addr\nS:Set IP addr,follow ip address\nH:Help\r\n");
>     break;
> 
> default:
>     shellPrint(&shell, "Param Error, Input correct parameters:G:Get,S:Set,H:Help\r\n");
>     break;
> }
> ```
> 
> } SHELL_EXPORT_CMD(SHELL_CMD_PERMISSION(0) | SHELL_CMD_TYPE(SHELL_TYPE_CMD_FUNC) | SHELL_CMD_DISABLE_RETURN, Server_IP, Server_IPEdit, 设置获取服务器IP地址\r\n格式 : Server_IP[cmd][params]); `

字符数据需要加单引号，必然会被认为是数字或者字符串，传递给函数的参数就不是你期望的了

```sh
Server_IP 'G'
```

上下键是三个字节的数据，你这个输出看着是有字符漏了，检测方法是复制一个字符串，粘贴到终端，看看是不是漏字符，如果漏字符的话，需要检查一下你的串口驱动

**Comment by Home-Laozang** [comment]
好的，谢谢大佬，我明天测试一下

**Comment by Home-Laozang** [comment]
您好，大佬，字符添加引号输入以后解决了该问题。另外，上下键测试是三个字符，我输入上键。得到的数据如下。
![image](https://github.com/NevermindZZT/letter-shell/assets/52019342/12173ca3-93bf-4483-b7f1-c8dca6ed57a3)
但是中断的行为不是历史命令。

**Comment by Home-Laozang** [comment]
解决了，是串口驱动的问题，使用空闲中断和双缓冲区导致的。多谢大佬
