### ISSUE TITLE
看源码里分组功能，但怎么实现和分组和关联

### ISSUE THREAD

**Issue by younguis** [NevermindZZT/letter-shell#180]
如果有成百个cmd测试命令，怎么实现分组和关联呢，类似多级菜单显得不乱。如果是链表很容易实现这种功能，不知道letter-shell如何实现这个功能，没有demo参考，网友们大多数例子都是简单的几条命令

**Comment by NevermindZZT** [comment]
shell_enhance 里面的 cmd_group 可以实现你的部分需求，readme 里面有使用的例子，可以试一下能否解决你的问题
