### ISSUE TITLE
请教一下，letter-shell是如何知道终端换行的呢?

### ISSUE THREAD

**Issue by FlyyingPiggy2020** [NevermindZZT/letter-shell#181]
举个极端的例子，如果终端的显示的宽度被拉小成了10个字节。
那么当我键入键值的时候，到第10个就需要换行显示。

在终端上它自己会处理换行,而我们是不知道终端上是否换行的。
但是当终端去解析退格键，或者方向键的时候它有不会自己去换行。

**Comment by lotoohe-space** [comment]
你好，邮件已收到，谢谢！

**Comment by NevermindZZT** [comment]
这个现在没有做处理，完善的做法应该是：shell 是有办法可以获取到终端的宽度和高度的，在获取到终端信息后，在结合当前 shell 的输入状态，控制终端退行

**Comment by FlyyingPiggy2020** [comment]
OK，谢谢回复。

**Comment by FlyyingPiggy2020** [comment]
我试了一下，可以用\b当成左键..然后右键改成打印光标后面的字节，并且用\b退格回去..
这样子可以实现换行。
![1](https://github.com/NevermindZZT/letter-shell/assets/62139687/eb4a2dd1-f939-443b-83a6-87a4835bee95)
![2](https://github.com/NevermindZZT/letter-shell/assets/62139687/fb5eccca-9c31-46e5-9775-da5d73c0d966)
