### ISSUE TITLE
STM32使用虚拟串口的问题

### ISSUE THREAD

**Issue by SkylerLiang** [NevermindZZT/letter-shell#189]
使用的单片机为STM32F103RCT6，用CubeMX生成工程，在使用UART发送以及UART中断接收时，可以正常使用，代码如下：
```C
short userShellWrite(char *data, unsigned short len)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)data, len, 0xFF);
    return len;
}
```
```C
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == huart1.Instance)
    {
        shellHandler(&shell, uartRxBuf);
    }
    HAL_UART_Receive_IT(&huart1, &uartRxBuf, 1);
}
```

但使用CubeMX生成的USB虚拟串口时，出现了错误，代码如下：
```C
short userShellWrite(char *data, unsigned short len)
{
	if (0 != CDC_Transmit_FS((uint8_t *)data, (uint16_t)len))
	{
		return 0;
	}
    return (short)len;
}
```
```C
static int8_t CDC_Receive_FS(uint8_t* Buf, uint32_t *Len)
{
  /* USER CODE BEGIN 6 */
	for (int i = 0; i < (*Len); i++)
	{
		shellHandler(&shell, (char)Buf[i]);
	}
  USBD_CDC_SetRxBuffer(&hUsbDeviceFS, &Buf[0]);
  USBD_CDC_ReceivePacket(&hUsbDeviceFS);
  return (USBD_OK);
  /* USER CODE END 6 */
}
```
显示如下：
![image](https://github.com/NevermindZZT/letter-shell/assets/62789882/bb413739-dc69-4736-b9a8-c6e553d86faa)
不显示用户名等内容
请问可能是什么导致的

**Comment by NevermindZZT** [comment]
看着是没啥问题，不过我没有试过虚拟串口，会不会有什么缓冲区之类的设置

**Comment by MengHuanzzz** [comment]
没用ST的驱动，你尝试一下cherryUSB，它比st的屎山好的多

**Comment by DragonYH** [comment]
同问题，现在解决了吗

**Comment by SkylerLiang** [comment]
> 同问题，现在解决了吗

还没有，后面没有研究这个问题了

**Comment by DragonYH** [comment]
搞定了，是官方库的传输函数连续使用会有问题
![QQ20240819-132133](https://github.com/user-attachments/assets/4437a2db-9db8-4a21-8579-3fe25fc5c636)
![QQ20240819-132229](https://github.com/user-attachments/assets/f6eac39d-97f0-4014-8f5f-7012598fa76e)
![QQ20240819-132243](https://github.com/user-attachments/assets/bc4ebfa4-9cb6-40b3-90e2-61ea9c11f57b)
![QQ20240819-132434](https://github.com/user-attachments/assets/d2f1ff74-8115-4689-8c9e-98fdebe9165b)

把rxFlag和rxBuf声明为全局变量即可

**Comment by SkylerLiang** [comment]
明白了，多谢
