### ISSUE TITLE
readme疑问

### ISSUE THREAD

**Issue by xupenghu** [NevermindZZT/letter-shell#19]
readme的说明第一条
对于中断方式使用shell，不用定义shell->read，但需要在中断中调用shellHandler

但是在shellTask()函数中就有这样一段代码
```
if` (shell->read == NULL)
    {
        shellDisplay(shell, "error: shell.read must be defined\r\n");
        while (1) ;
    }
```

不知道这里怎么理解

**Comment by xupenghu** [comment]
理解作者的意思了。其实有三种读数据的方式 
1 裸机下的while（1）中轮询
2 rtos下单独创建一个任务，读函数需要做成阻塞读取
3 采用中断直接读取
不知道是不是这个意思
另还有一个疑问 中断中对串口数据处理，可能会造成系统异常，不知道作者有没有出现过，我觉得这么做会有风险。

**Comment by NevermindZZT** [comment]
是这个样子的，3种方式
中断方式确实是容易引发异常，所以一般不建议采用这种方式

**Comment by xupenghu** [comment]
嗯 那我觉得应该改下readme文件，应该有很多新手会产生我这样的疑问。
