### ISSUE TITLE
关于使用中断和DMA发送数据遇到的问题

### ISSUE THREAD

**Issue by TommyLee9527** [NevermindZZT/letter-shell#190]
![image](https://github.com/NevermindZZT/letter-shell/assets/80229601/cd11f1f1-1bf7-4dcf-b06d-e583de0c34a7)
这是发送数据的函数
![image](https://github.com/NevermindZZT/letter-shell/assets/80229601/f2670aa1-8400-437a-9761-7f79bd38b17d)
这是中断回调函数

现在遇到个问题，调试过程中发现：最开始几次调用发送数据函数后不能进中断，无法释放信号量导致后面数据发不出去，DMA也是一样的情况，最后不在调用发送数据的函数之后才会进一次中断。一直怀疑shellHandle() 把中断禁用了，但是找了半天也没有找到，现在有点怀疑人生了。。。

**Comment by NevermindZZT** [comment]
这里一个一个字节发数据，会出现多个线程同时调用 shellWrite 被阻塞的情况吧

**Comment by TommyLe1** [comment]
> 这里一个一个字节发数据，会出现多个线程同时调用 shellWrite 被阻塞的情况吧
> 
> shellHandle 会调用里面都是 shell 的逻辑，不会操作中断的

现在的情况是单字节发送或者多字节发送，调用发送函数之后不会进中断回调函数。没搞明白问题出在哪里了。。。
有时间再调试下试试
