### ISSUE TITLE
【已解决】STM32使用HAL库移植FreeRTOS后再移植Letter Shell后无法输入的BUG

### ISSUE THREAD

**Issue by cdxiaohuihui** [NevermindZZT/letter-shell#192]
使用STM32F103C8T6进行移植，移植完成后打印了Letter Shell的头内容，但是一直无法输入，经过debug调试，发现串口接收到了电脑发送过来的数据，但是一直无法回显，原因是`shell.c`文件`shellTask`函数中`if (shell->read && shell->read(&data, 1) == 1)`此行导致，`shellTask`函数的原型为：
```
void shellTask(void *param)
{
    Shell *shell = (Shell *)param;
    char data;
#if SHELL_TASK_WHILE == 1
    while(1)
    {
#endif
        if (shell->read && shell->read(&data, 1) == 1) // 此行存在问题
        {
            shellHandler(shell, data);
        }
#if SHELL_TASK_WHILE == 1
    }
#endif
}
```
`shell->read`最终指向了HAL库函数中的`HAL_StatusTypeDef HAL_UART_Receive(UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size, uint32_t Timeout)`，返回值为`HAL_StatusTypeDef`类型，通过查看`HAL_StatusTypeDef`的定义，定义原型为：
```
typedef enum
{
  HAL_OK       = 0x00U,
  HAL_ERROR    = 0x01U,
  HAL_BUSY     = 0x02U,
  HAL_TIMEOUT  = 0x03U
} HAL_StatusTypeDef;
```
通过`HAL_StatusTypeDef`的原型可知使用`HAL_UART_Receive(UART_HandleTypeDef *huart, uint8_t *pData, uint16_t Size, uint32_t Timeout)`函数接收串口数据成功时返回值为`HAL_OK`，而shellTask函数中`shell->read(&data, 1) == 1`为`HAL_ERROR`，所以不会执行shellHandler(shell, data)函数，导致不能输入。通过将`shellTask`函数中`if (shell->read && shell->read(&data, 1) == 1)`修改为`if (shell->read && shell->read(&data, 1) == **HAL_OK**)`即可正常输入。修改后的`shellTask`的函数如下：
```
void shellTask(void *param)
{
    Shell *shell = (Shell *)param;
    char data;
#if SHELL_TASK_WHILE == 1
    while(1)
    {
#endif
        if (shell->read && shell->read(&data, 1) == HAL_OK) // 修改此行为HAL_OK
        {
            shellHandler(shell, data);
        }
#if SHELL_TASK_WHILE == 1
    }
#endif
}
```

**Comment by Suaig** [comment]
这个不能算bug。而且你也不应该改他源代码，你这个问题在于，你的返回值没有按照他的回调函数就设计。我移植的没问题。
short userShellRead(char *data, unsigned short len)
{
    //return serialReceive(&debugSerial, (uint8_t *)data, len, 0);
		if(HAL_UART_Receive(&huart1, (uint8_t*)data, len, 20) == HAL_OK) //这一部分待优化，阻塞式影响操作系统效率
		{
			return len;
		}
		else
		{
			return 0;
		}
}

**Comment by lotoohe-space** [comment]
你好，邮件已收到，谢谢！
