### ISSUE TITLE
请教一个伴生对象模式下注册的0x04000000的键值是哪个按键呀?

### ISSUE THREAD

**Issue by TommyLee9527** [NevermindZZT/letter-shell#199]
文件 log.c 倒数第二行 这一句
SHELL_EXPORT_KEY(SHELL_CMD_PERMISSION(0), 0x04000000, logSwitchLevel, switch log level);
注册的是哪个按键?

**Comment by NevermindZZT** [comment]
组合键 Ctrl＋D

**Comment by TommyLee9527** [comment]
> 组合键 Ctrl＋D
这个是shell交互的规则吗? 有什么对照表可以查吗?

**Comment by TommyLee9527** [comment]
![image](https://github.com/user-attachments/assets/6379770b-befc-41ea-a027-438122ea0eee)
这个方法好像工作也不太正常, 函数需要传参数进去的, 但是按键触发是无法传参的吧? 我调试的时候直接在第二行return出来了.

**Comment by NevermindZZT** [comment]
> ![image](https://github.com/user-attachments/assets/6379770b-befc-41ea-a027-438122ea0eee)
> 这个方法好像工作也不太正常, 函数需要传参数进去的, 但是按键触发是无法传参的吧? 我调试的时候直接在第二行return出来了.

log 初始化的时候传递 shell 对象进去了吗，快捷键的函数调用的时候都会传递 shell 作为参数的

**Comment by TommyLee9527** [comment]
> > ![image](https://private-user-images.githubusercontent.com/80229601/379089018-6379770b-befc-41ea-a027-438122ea0eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODU4MDQsIm5iZiI6MTcyOTY4NTUwNCwicGF0aCI6Ii84MDIyOTYwMS8zNzkwODkwMTgtNjM3OTc3MGItYmVmYy00MWVhLWEwMjctNDM4MTIyZWEwZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZmUzZmYzMjBhYWZiOWQ4YzliYjY4YmZkOGM3ZDMzY2ZlZDJkYzkxMmUyMWZkYjYxNDE2MjJhMmNmMzQ3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SS_veNBzsflHb-dxoLv0eR-1FmzMxnIrmOoQjXZYGeA)
> > 这个方法好像工作也不太正常, 函数需要传参数进去的, 但是按键触发是无法传参的吧? 我调试的时候直接在第二行return出来了.
> 
> log 初始化的时候传递 shell 对象进去了吗，快捷键的函数调用的时候都会传递 shell 作为参数的

log初始化的时候传了，但是这里的shell根本不是我初始化时候的shell，而是函数参数shell啊，此时函数参数应该是空的吧？

**Comment by NevermindZZT** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/80229601/379089018-6379770b-befc-41ea-a027-438122ea0eee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODU4MDQsIm5iZiI6MTcyOTY4NTUwNCwicGF0aCI6Ii84MDIyOTYwMS8zNzkwODkwMTgtNjM3OTc3MGItYmVmYy00MWVhLWEwMjctNDM4MTIyZWEwZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEyMTE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZmUzZmYzMjBhYWZiOWQ4YzliYjY4YmZkOGM3ZDMzY2ZlZDJkYzkxMmUyMWZkYjYxNDE2MjJhMmNmMzQ3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SS_veNBzsflHb-dxoLv0eR-1FmzMxnIrmOoQjXZYGeA)
> > > 这个方法好像工作也不太正常, 函数需要传参数进去的, 但是按键触发是无法传参的吧? 我调试的时候直接在第二行return出来了.
> > 
> > 
> > log 初始化的时候传递 shell 对象进去了吗，快捷键的函数调用的时候都会传递 shell 作为参数的
> 
> log初始化的时候传了，但是这里的shell根本不是我初始化时候的shell，而是函数参数shell啊，此时函数参数应该是空的吧？

`logRegister(&log, &shell);` 应该是要在 `shellInit` 之后调用，命令函数是 shell 调用的，调用的时候会传递活动 shell 对象进去
