### ISSUE TITLE
关于SHELL_TypeDef的status中的位域定义

### ISSUE THREAD

**Issue by donggua127** [NevermindZZT/letter-shell#30]
平台：TMS320C6748
编译器：TI C6000 v7.4.4
struct
    {
        char inputMode : 2;                               /**< 输入模式 */
        char tabFlag : 1;                                    /**< tab标志 */
        char authFlag : 1;                                 /**< 密码标志 */
    } status;                                                   /**< shell状态 */
对于tagFlag和authFlag编译器会提示警告“#109-D signed bit field of length 1”，也就是定义了一个1bit的有符号数据，也就是说只有一个符号位。
而对于inputMode，相当于一个2bit有符号数，在完成shell->status.inputMode = SHELL_ANSI_CSI;之后，(unsigned char)(shell->status.inputMode)的值为-2，shellAnsi函数永远无法正确执行了，shell挂死。

测试场景，按上下键可以触发。

修改方式：
    struct
    {
        unsigned char inputMode : 2;                                     /**< 输入模式 */
        unsigned char tabFlag : 1;                                       /**< tab标志 */
        unsigned char authFlag : 1;                                      /**< 密码标志 */
    } status;        

@NevermindZZT

**Comment by NevermindZZT** [comment]
感谢指正
