### ISSUE TITLE
配置有密码的情况下，初始化，shellSetUser函数shell->parser.param[1]还未赋值，导致崩溃。

### ISSUE THREAD

**Issue by mrxsean** [NevermindZZT/letter-shell#48]
static void shellSetUser(Shell *shell, const ShellCommand *user)
{
    shell->info.user = user;
    shell->status.isChecked = 1;
    ((user->data.user.password && strlen(user->data.user.password) != 0)
        && (shell->parser.paramCount == 1
            || strcmp(user->data.user.password, shell->parser.param[1]) != 0))
     ? 0 : 1;
        
#if SHELL_CLS_WHEN_LOGIN == 1
    shellWriteString(shell, shellText[SHELL_TEXT_CLEAR_CONSOLE]);
#endif
#if SHELL_SHOW_INFO == 1
    if (shell->status.isChecked)
    {
        shellWriteString(shell, shellText[SHELL_TEXT_INFO]);
    }
#endif
}

配置有密码的情况下，初始化，该函数shell->parser.param[1]还未赋值，导致崩溃。

**Comment by NevermindZZT** [comment]
感谢反馈，已经修复了，拉取最新代码即可

**Comment by mrxsean** [comment]
shell.h和shell_companion.h相互包含，以至于引起一些警告，对于强迫症用户很难受，建议吧shell_companion.h包含在shell.c里面

**Comment by NevermindZZT** [comment]
确实是不太好，后面改一下
