### ISSUE TITLE
尾行模式下无法输入指令

### ISSUE THREAD

**Issue by liuyucat** [NevermindZZT/letter-shell#63]
测试过程中遇见了一个bug，一个任务周期性（1s）调用尾行模式打印调试信息，此时如果输入几次指令后，上下键翻过几次历史输入，然后输入enter，再次快速点击tab键，会有概率出现只有尾行模式打印信息，而无法输入指令，无法执行指令，而且概率相当高，希望能分析一下原因。

**Comment by NevermindZZT** [comment]
@liuyucat 我这里没有复现，你是用的串口吗，可能需要确认下串口驱动会不会在快速读写的情况下的表现

**Comment by liuyucat** [comment]
是的 串口应该没有问题的 串口接收中断还是可以进的 就是在函数shellWriteEndLine里面的shell->parser.length和shell->parser.cursor值不会变化了
void shellWriteEndLine(Shell *shell, char *buffer, int len)
{
    if (!shell->status.isActive)
    {
        shellWriteString(shell, shellText[SHELL_TEXT_CLEAR_LINE]);
    }
    while (len --)
    {
        shell->write(*buffer++);
    }
    if (!shell->status.isActive)
    {
        shellWriteCommandLine(shell, 0);
        if (shell->parser.length > 0)
        {
            shellWriteString(shell, shell->parser.buffer);
            for (short i = 0; i < shell->parser.length - shell->parser.cursor; i++)
            {
                shell->write('\b');
            }
        }
    }
}

**Comment by liuyucat** [comment]
整个操作过程如下：































 _         _   _                  _          _ _ 
| |    ___| |_| |_ ___ _ __   ___| |__   ___| | |
| |   / _ \ __| __/ _ \ '__| / __| '_ \ / _ \ | |
| |__|  __/ |_| ||  __/ |    \__ \ | | |  __/ | |
|_____\___|\__|\__\___|_|    |___/_| |_|\___|_|_|

Build:       Dec  3 2020 20:31:07
Version:     3.0.6
Copyright:   (c) 2020 Letter

letter:/$ setVar DebugMsgFlg 1
DebugMsgFlg = 1, 0x00000001

Period Func Trig!
Period Func Trig!
Period Func Trig!
Period Func Trig!
Period Func Trig!
letter:/$ setVar DebugMsgFlg 1
DebugMsgFlg = 1, 0x00000001

letter:/$ setVar DebugMsgFlg 1
DebugMsgFlg = 1, 0x00000001

Period Func Trig!
letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

Period Func Trig!
letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

Period Func Trig!
letter:/$ 
letter:/$ 
Period Func Trig!
letter:/$ setVar DebugMsgFlg 1
DebugMsgFlg = 1, 0x00000001

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

Period Func Trig!
letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Version               CMD   --------  Show Software Version
tasklist              CMD   --------  Display state table of FreeRTOS task
cx9261                CMD   --------  CX9261 Config Command Group

letter:/$ 
Command List:
logSetLevel           CMD   --------  set log level
hexdump               CMD   --------  hex dump
setVar                CMD   --------  set var
help                  CMD   --------  show command info
users                 CMD   --------  list all user
cmds                  CMD   --------  list all cmd
vars                  CMD   --------  list all var
keys                  CMD   --------  list all key
clear                 CMD   --------  clear console
Period Func Trig!
Period Func Trig!
Period Func Trig!
Period Func Trig!
Period Func Trig!
letter:/$ 
此时无法输入，也没有echo，但是secureCRT输入串口中断仍可以进。
平台是Zynq7020，FreeRTOS实时内核。

**Comment by NevermindZZT** [comment]
我再测试一下

**Comment by liuyucat** [comment]
解决了 确实是串口收驱动函数写的不够好 导致低优先级任务被阻塞死
感谢！

**Comment by NevermindZZT** [comment]
解决了就好
