### ISSUE TITLE
master分支中的demo/stm32-freertos/shell_port.c文件内容错误

### ISSUE THREAD

**Issue by AnthonyYMH** [NevermindZZT/letter-shell#83]
在master分支中，Shell结构体中的write/read函数指针已经做出了修改，但是在demo/stm32-freertos/shell_port.c文件中，接口函数并未做出对应的修改。

**Comment by AnthonyYMH** [comment]
发现从3.1版本也存在这个问题

**Comment by NevermindZZT** [comment]
还是之前的，没有更新，要改的

**Comment by AnthonyYMH** [comment]
想请问一下，哪个分支比较稳定呢？master还是3.1？谢谢~建议加上不同版本的更新说明。

**Comment by NevermindZZT** [comment]
> 想请问一下，哪个分支比较稳定呢？master还是3.1？谢谢~建议加上不同版本的更新说明。

shell3.0算是稳定的分支了，有做release的

**Comment by AnthonyYMH** [comment]
我用了3.1，QAQ...

**Comment by NevermindZZT** [comment]
没啥大区别，都稳

**Comment by AnthonyYMH** [comment]
强啊，感谢大佬开源。
