### ISSUE TITLE
串口终端回显功能

### ISSUE THREAD

**Issue by kcx064** [NevermindZZT/letter-shell#95]
shell如何实现串口终端本地回显功能？我看readme里的动图有这个效果。crt软件自身有这个功能。那么这个shell本身有这个功能吗？我在用户接口函数的接收中加了一个接收后发送函数，但是实现的效果和希望的差的很远。

**Comment by NevermindZZT** [comment]
shell本身有回显，你是中断方式使用吗，在中断中调用shellHandler，然后实现shell.write就行，不太清楚你遇到的问题，如果有图说明会比较清晰

**Comment by kcx064** [comment]
谢谢. 我到了原因, 我在移植过程中直接使用了getchar函数导致了这个问题.
